spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/is6769/NXB-ConfigVault
          search-paths:
            - '{application}'

logging:
  level:
    org.springframework.cloud.config.server: TRACE

server:
  port: 8888
